import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={' ' + inter.className}>
        <header>
           <h1>Joel Carr</h1> 
           <h1>JC</h1>
           </header>
        {children}
        <footer>
          <div>
            <h4>PDF Resume</h4>
            <h4>Projects</h4> 
            <h4>Blog</h4>  
          </div>
          <div>
            <h4>PDF Resume</h4>
            <h4>Projects</h4> 
            <h4>Blog</h4>  
          </div>
        </footer>
      </body>
    </html> 
  )
}
